# Flutter Code Guard Configuration
# Industry-specific coding rules and standards configuration

# =============================================================================
# GENERAL SETTINGS
# =============================================================================
version: "1.0.0"
config_name: "Industry Standards Configuration"
author: "Flutter Code Guard Team"
created_at: "2024-01-01"

# Enable/disable the analyzer
enabled: true

# Analysis scope
include:
  - "lib/**/*.dart"
  - "test/**/*.dart"
  - "integration_test/**/*.dart"

exclude:
  - "**/*.g.dart"      # Generated files
  - "**/*.freezed.dart" # Freezed generated files
  - "**/*.pb*.dart"    # Protocol buffer generated files
  - "build/**"         # Build output
  - ".dart_tool/**"    # Dart tools

# =============================================================================
# INDUSTRY-SPECIFIC RULE SETS
# =============================================================================

# Select your industry domain (uncomment one)
industry_domain: "general"  # Options: fintech, healthcare, ecommerce, gaming, enterprise, general

# Industry-specific configurations
industry_rules:
  
  # FINTECH/BANKING RULES
  fintech:
    description: "Financial services coding standards with security and precision focus"
    mandatory_rules:
      - "no_double_for_money"           # Use BigInt/Decimal for monetary values
      - "require_money_validation"      # Validate all financial amounts
      - "secure_random_ids"            # Use cryptographically secure ID generation
      - "audit_trail_required"         # All financial operations must be logged
      - "immutable_financial_data"     # Financial data must be immutable
      - "currency_code_validation"     # Validate ISO currency codes
      - "transaction_state_machine"    # Enforce valid state transitions
      - "pci_compliance_checks"        # PCI DSS compliance validation
    
    severity_levels:
      no_double_for_money: "error"
      require_money_validation: "error"
      secure_random_ids: "warning"
      audit_trail_required: "error"
      immutable_financial_data: "error"
      currency_code_validation: "warning"
      transaction_state_machine: "error"
      pci_compliance_checks: "error"
    
    custom_patterns:
      - pattern: "double.*[Aa]mount|[Aa]mount.*double"
        message: "❌ Use BigInt or Decimal for monetary amounts, never double/float"
        severity: "error"
      
      - pattern: "Random\\(\\)|math\\.Random"
        message: "⚠️  Use cryptographically secure random for financial operations"
        severity: "warning"
      
      - pattern: "print\\(.*[Pp]assword|print\\(.*[Tt]oken|print\\(.*[Kk]ey"
        message: "🚨 Never log sensitive financial data"
        severity: "error"

  # HEALTHCARE RULES  
  healthcare:
    description: "Healthcare coding standards with HIPAA compliance and privacy focus"
    mandatory_rules:
      - "hipaa_compliance"             # HIPAA privacy requirements
      - "pii_encryption_required"      # Personally identifiable information must be encrypted
      - "access_audit_logging"         # Log all access to patient data
      - "data_anonymization"           # Support for data anonymization
      - "secure_data_transmission"     # Encrypt data in transit
      - "patient_consent_validation"   # Validate patient consent for data usage
      - "medical_data_validation"      # Validate medical data formats
      - "gdpr_compliance"              # GDPR compliance for EU patients
    
    severity_levels:
      hipaa_compliance: "error"
      pii_encryption_required: "error"
      access_audit_logging: "error"
      data_anonymization: "warning"
      secure_data_transmission: "error"
      patient_consent_validation: "error"
      medical_data_validation: "warning"
      gdpr_compliance: "warning"
    
    custom_patterns:
      - pattern: "ssn|social.security|patient.*name"
        message: "🏥 Patient PII must be encrypted and access-controlled"
        severity: "error"
      
      - pattern: "http://.*patient|http://.*medical"
        message: "🔒 Use HTTPS for all medical data transmission"
        severity: "error"

  # E-COMMERCE RULES
  ecommerce:
    description: "E-commerce coding standards with scalability and performance focus"
    mandatory_rules:
      - "order_state_validation"       # Validate order state transitions
      - "inventory_consistency"        # Ensure inventory consistency
      - "payment_security"            # Secure payment processing
      - "cart_session_management"     # Proper cart session handling
      - "price_calculation_accuracy"   # Accurate price calculations
      - "shipping_validation"         # Validate shipping addresses
      - "performance_optimization"     # Optimize for high traffic
      - "caching_strategies"          # Implement proper caching
    
    severity_levels:
      order_state_validation: "error"
      inventory_consistency: "error"
      payment_security: "error"
      cart_session_management: "warning"
      price_calculation_accuracy: "error"
      shipping_validation: "warning"
      performance_optimization: "info"
      caching_strategies: "info"

  # GAMING RULES
  gaming:
    description: "Gaming industry standards with performance and real-time requirements"
    mandatory_rules:
      - "performance_critical_methods"  # Optimize performance-critical code
      - "memory_management"            # Efficient memory usage
      - "real_time_constraints"       # Meet real-time performance requirements
      - "player_data_integrity"       # Maintain player data consistency
      - "anti_cheat_measures"         # Implement anti-cheat validations
      - "game_state_synchronization"  # Proper game state sync
      - "leaderboard_accuracy"        # Accurate scoring and rankings
      - "session_management"          # Handle player sessions properly
    
    severity_levels:
      performance_critical_methods: "warning"
      memory_management: "warning"
      real_time_constraints: "error"
      player_data_integrity: "error"
      anti_cheat_measures: "warning"
      game_state_synchronization: "error"
      leaderboard_accuracy: "error"
      session_management: "warning"

  # ENTERPRISE RULES
  enterprise:
    description: "Enterprise coding standards with compliance and audit requirements"
    mandatory_rules:
      - "role_based_access_control"   # Implement RBAC properly
      - "audit_logging"               # Comprehensive audit logging
      - "data_retention_policies"     # Follow data retention rules
      - "compliance_validation"       # Meet regulatory compliance
      - "security_best_practices"     # Follow enterprise security standards
      - "error_handling_standards"    # Consistent error handling
      - "documentation_requirements"  # Proper code documentation
      - "testing_coverage"            # Maintain test coverage standards
    
    severity_levels:
      role_based_access_control: "error"
      audit_logging: "error"
      data_retention_policies: "warning"
      compliance_validation: "error"
      security_best_practices: "error"
      error_handling_standards: "warning"
      documentation_requirements: "info"
      testing_coverage: "warning"

# =============================================================================
# TERMINAL UI CONFIGURATION
# =============================================================================

terminal_ui:
  # Enable beautiful terminal UI
  enabled: true
  
  # Color scheme
  colors:
    primary: "#3498db"      # Blue
    success: "#2ecc71"      # Green
    warning: "#f39c12"      # Orange
    error: "#e74c3c"        # Red
    info: "#9b59b6"         # Purple
    text: "#ecf0f1"         # Light gray
    background: "#2c3e50"   # Dark blue
    accent: "#1abc9c"       # Teal

  # UI Elements
  icons:
    error: "❌"
    warning: "⚠️"
    info: "ℹ️"
    success: "✅"
    loading: "🔄"
    file: "📄"
    folder: "📁"
    security: "🔒"
    performance: "⚡"
    money: "💰"
    healthcare: "🏥"
    gaming: "🎮"
    enterprise: "🏢"
    ecommerce: "🛒"

  # Progress indicators
  progress:
    style: "bar"            # Options: bar, spinner, dots
    show_percentage: true
    show_eta: true
    animation_speed: 100    # milliseconds

  # Message formatting
  formatting:
    max_line_length: 120
    indent_size: 2
    show_line_numbers: true
    show_file_path: true
    highlight_keywords: true
    group_by_severity: true
    show_rule_explanations: true

  # Premium UI features
  premium_features:
    animated_messages: true
    syntax_highlighting: true
    interactive_fixes: true
    code_suggestions: true
    real_time_preview: true
    smart_notifications: true

# =============================================================================
# CODE QUALITY METRICS
# =============================================================================

quality_metrics:
  # Minimum quality thresholds
  thresholds:
    complexity_per_method: 10
    lines_per_method: 50
    lines_per_class: 500
    test_coverage_percentage: 80
    documentation_coverage: 70
    security_score: 85
    maintainability_index: 70

  # Quality scoring
  scoring:
    weights:
      security: 30          # 30% weight
      maintainability: 25   # 25% weight
      performance: 20       # 20% weight
      readability: 15       # 15% weight
      testing: 10           # 10% weight

  # Code smells detection
  code_smells:
    - "long_methods"
    - "large_classes"
    - "duplicate_code"
    - "complex_conditionals"
    - "magic_numbers"
    - "god_objects"
    - "feature_envy"
    - "data_clumps"

# =============================================================================
# NOTIFICATION SETTINGS
# =============================================================================

notifications:
  # When to show notifications
  triggers:
    on_error: true
    on_warning: true
    on_improvement_suggestion: true
    on_quality_score_change: true
    on_new_best_practices: true

  # Notification styles
  styles:
    desktop_notifications: true
    sound_alerts: false
    terminal_popups: true
    status_bar_updates: true

  # Frequency limits
  frequency:
    max_notifications_per_minute: 5
    cooldown_period_seconds: 30
    batch_similar_messages: true

# =============================================================================
# INTEGRATION SETTINGS
# =============================================================================

integrations:
  # IDE integrations
  vscode:
    enabled: true
    show_inline_hints: true
    auto_fix_suggestions: true
    
  android_studio:
    enabled: true
    toolbar_integration: true
    
  intellij:
    enabled: true
    
  # CI/CD integrations
  github_actions:
    enabled: true
    fail_on_error: true
    comment_on_pr: true
    
  gitlab_ci:
    enabled: true
    
  jenkins:
    enabled: true

# =============================================================================
# ADVANCED FEATURES
# =============================================================================

advanced_features:
  # AI-powered suggestions
  ai_suggestions:
    enabled: true
    confidence_threshold: 0.8
    learn_from_fixes: true
    
  # Custom rule creation
  custom_rules:
    enabled: true
    rule_sharing: true
    community_rules: true
    
  # Performance monitoring
  performance_monitoring:
    track_analysis_time: true
    optimize_for_large_codebases: true
    cache_analysis_results: true
    
  # Reporting
  reporting:
    generate_html_reports: true
    export_metrics: true
    trend_analysis: true
    team_dashboards: true

# =============================================================================
# TEAM COLLABORATION
# =============================================================================

team_settings:
  # Shared configuration
  shared_config:
    enabled: true
    sync_rules_across_team: true
    enforce_team_standards: true
    
  # Code review integration
  code_review:
    auto_review_comments: true
    suggest_reviewers: true
    block_merge_on_violations: true
    
  # Learning and improvement
  learning:
    track_common_issues: true
    suggest_training_topics: true
    measure_code_quality_trends: true